[package]
name = "dig"
version = "0.1.0"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
edition = "2018"
description = "no dig no gain"
keywords = ["dig"]
readme = "README.md"
repository = "https://github.com/baoyachi/dig-rs"
license = "MIT AND Apache-2.0"


[dependencies]
